In [1]:
import pandas as pd
from sklearn.cluster import KMeans

df = pd.read_csv("customer_data.csv")

X = df[["Income","SpendingScore"]]

kmeans = KMeans(n_clusters=3, random_state=42)

df["Segment"] = kmeans.fit_predict(X)

print(df[["CustomerID","Segment"]])

   CustomerID  Segment
0           1        2
1           2        1
2           3        0
3           4        0
4           5        1
5           6        0
6           7        1
7           8        0
8           9        1
9          10        0


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X = df[["Age","Income","SpendingScore"]]
y = df["Purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression()

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 1.0


In [3]:
import numpy as np
import random

products = ["Mobile", "Laptop", "Headphone"]

Q = np.zeros((3,3))

alpha = 0.1
gamma = 0.9
epsilon = 0.2

for episode in range(1000):

    state = random.randint(0,2)

    if random.random() < epsilon:
        action = random.randint(0,2)
    else:
        action = np.argmax(Q[state])

    reward = 10 if state == action else -2

    Q[state,action] = Q[state,action] + alpha * (
        reward + gamma * np.max(Q[action])
        - Q[state,action]
    )

print("Q Table:")
print(Q)

print("\nRecommendations")

for i in range(3):
    recommendation = products[np.argmax(Q[i])]
    print(f"Customer Segment {i}: {recommendation}")

Q Table:
[[95.28915128 55.04605149 64.90567825]
 [83.14669616 55.84755029 60.63873065]
 [65.60136196 55.89148937 94.24036097]]

Recommendations
Customer Segment 0: Mobile
Customer Segment 1: Mobile
Customer Segment 2: Headphone
