In [1]:
import numpy as np
import random

# Grid size
grid_size = 5

# Parameters
alpha = 0.1      # Learning rate
gamma = 0.9      # Discount factor
epsilon = 0.2    # Exploration rate
episodes = 1000

# Actions
actions = ["up", "down", "left", "right"]

# Q-table
q_table = np.zeros((grid_size, grid_size, len(actions)))

# Start and Goal
start = (0, 0)
goal = (4, 4)

# Reward function
def get_reward(state):
    if state == goal:
        return 100
    return -1

# Next state
def get_next_state(state, action):
    row, col = state

    if action == 0:      # up
        row = max(row - 1, 0)
    elif action == 1:    # down
        row = min(row + 1, grid_size - 1)
    elif action == 2:    # left
        col = max(col - 1, 0)
    elif action == 3:    # right
        col = min(col + 1, grid_size - 1)

    return (row, col)

# Training
for episode in range(episodes):

    state = start

    while state != goal:

        if random.uniform(0, 1) < epsilon:
            action = random.randint(0, 3)
        else:
            action = np.argmax(q_table[state])

        next_state = get_next_state(state, action)

        reward = get_reward(next_state)

        old_q = q_table[state][action]

        next_max = np.max(q_table[next_state])

        new_q = old_q + alpha * (
            reward + gamma * next_max - old_q
        )

        q_table[state][action] = new_q

        state = next_state

# Testing learned path
print("Optimal Path:")

state = start
path = [state]

while state != goal:
    action = np.argmax(q_table[state])
    state = get_next_state(state, action)
    path.append(state)

print(path)

print("\nQ-Table:")
print(q_table)

Optimal Path:
[(0, 0), (1, 0), (1, 1), (1, 2), (2, 2), (2, 3), (3, 3), (3, 4), (4, 4)]

Q-Table:
[[[ 3.70401066e+01  4.26126590e+01  3.64299765e+01  4.20008776e+01]
  [ 2.38866854e+01  2.70551271e+01  2.59957195e+00  4.84496129e+01]
  [ 1.40320091e+01  5.49538378e+01  2.27621172e+01  6.35808237e+00]
  [-5.85198506e-01  4.12472124e+01 -5.24952866e-01 -3.98754181e-01]
  [-4.90099501e-01 -4.73282200e-01  6.13421803e+00 -2.67971866e-01]]

 [[ 3.68171102e+01  4.70002858e+01  4.15208714e+01  4.84585100e+01]
  [ 4.11948769e+01  5.46923532e+01  4.24356617e+01  5.49539000e+01]
  [ 4.80776754e+01  6.21710000e+01  4.83351177e+01  6.17147902e+01]
  [ 1.02781512e+01  7.01890605e+01  1.86995264e+01  3.59331462e+00]
  [-2.97010000e-01  4.58457620e+01  5.91416377e+00  2.64642910e+00]]

 [[ 1.07017500e+01 -7.55702847e-01  8.35777988e+00  5.47815325e+01]
  [ 2.23861520e+01  8.02973212e+00  2.66406490e+01  6.21709938e+01]
  [ 5.46384133e+01  6.97637670e+01  5.47741966e+01  7.01900000e+01]
  [ 6.16993207e